---
swagger: "2.0"
info:
  version: "v1"
  title: "BringAlong Server REST API"
schemes:
- "https"
paths:
  /marketplace/v1/bringdemand:
    post:
      operationId: "saveBringDemand"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/BringDemandEto"
  /marketplace/v1/bringdemand/search:
    post:
      operationId: "findBringDemands"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/PageBringDemandEto"
  /marketplace/v1/bringdemand/{id}:
    get:
      operationId: "getBringDemand"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/BringDemandEto"
    delete:
      operationId: "deleteBringDemand"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      responses:
        default:
          description: "successful operation"
  /security/v1/csrftoken:
    get:
      operationId: "getCsrfToken"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/CsrfToken"
  /security/v1/currentuser:
    get:
      operationId: "getCurrentUser"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/UserProfileTo"
  /usermanagement/v1/user:
    post:
      operationId: "saveUser"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/UserEto"
  /usermanagement/v1/user/cto/{id}:
    get:
      operationId: "getUserCto"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/UserCto"
  /usermanagement/v1/user/{id}:
    get:
      operationId: "getUser"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/UserEto"
definitions:
  Address:
    type: "object"
    properties:
      streetAndNumber:
        type: "string"
      plz:
        type: "string"
      city:
        type: "string"
      additionalInformation:
        type: "string"
  AddressEto:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      modificationCounter:
        type: "integer"
        format: "int32"
      streetAndNumber:
        type: "string"
      plz:
        type: "string"
      city:
        type: "string"
      additionalInformation:
        type: "string"
  BringDemandEto:
    type: "object"
    required:
    - "currency"
    - "item"
    - "userId"
    properties:
      id:
        type: "integer"
        format: "int64"
      modificationCounter:
        type: "integer"
        format: "int32"
      item:
        type: "string"
      dropHint:
        type: "string"
      deadline:
        type: "string"
        format: "date-time"
      estimatedAmount:
        type: "integer"
        format: "int32"
      currency:
        type: "string"
      acceptedByUser:
        type: "integer"
        format: "int64"
      userId:
        type: "integer"
        format: "int64"
  CsrfToken:
    type: "object"
    properties:
      headerName:
        type: "string"
      parameterName:
        type: "string"
      token:
        type: "string"
  Page:
    type: "object"
    properties:
      totalPages:
        type: "integer"
        format: "int32"
      totalElements:
        type: "integer"
        format: "int64"
      size:
        type: "integer"
        format: "int32"
      content:
        type: "array"
        items:
          type: "object"
      number:
        type: "integer"
        format: "int32"
      sort:
        $ref: "#/definitions/Sort"
      numberOfElements:
        type: "integer"
        format: "int32"
      first:
        type: "boolean"
      pageable:
        $ref: "#/definitions/Pageable"
      last:
        type: "boolean"
      empty:
        type: "boolean"
  PageBringDemandEto:
    type: "object"
    properties:
      totalPages:
        type: "integer"
        format: "int32"
      totalElements:
        type: "integer"
        format: "int64"
      size:
        type: "integer"
        format: "int32"
      content:
        type: "array"
        items:
          $ref: "#/definitions/BringDemandEto"
      number:
        type: "integer"
        format: "int32"
      sort:
        $ref: "#/definitions/Sort"
      numberOfElements:
        type: "integer"
        format: "int32"
      first:
        type: "boolean"
      pageable:
        $ref: "#/definitions/Pageable"
      last:
        type: "boolean"
      empty:
        type: "boolean"
  Pageable:
    type: "object"
    properties:
      offset:
        type: "integer"
        format: "int64"
      sort:
        $ref: "#/definitions/Sort"
      paged:
        type: "boolean"
      unpaged:
        type: "boolean"
      pageNumber:
        type: "integer"
        format: "int32"
      pageSize:
        type: "integer"
        format: "int32"
  PaymentOptionEto:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      modificationCounter:
        type: "integer"
        format: "int32"
      type:
        type: "string"
        enum:
        - "PAYPAL"
        - "SEPA"
        - "PAYPALME"
      reference:
        type: "string"
  Sort:
    type: "object"
    properties:
      unsorted:
        type: "boolean"
      sorted:
        type: "boolean"
      empty:
        type: "boolean"
  UserCto:
    type: "object"
    properties:
      user:
        $ref: "#/definitions/UserEto"
      address:
        $ref: "#/definitions/AddressEto"
      acceptedPaymentOptions:
        type: "array"
        items:
          $ref: "#/definitions/PaymentOptionEto"
  UserEto:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      modificationCounter:
        type: "integer"
        format: "int32"
      login:
        type: "string"
      surname:
        type: "string"
      possiblePaymentOptions:
        type: "array"
        items:
          type: "string"
          enum:
          - "PAYPAL"
          - "SEPA"
          - "PAYPALME"
      forename:
        type: "string"
      address:
        $ref: "#/definitions/Address"
  UserProfileTo:
    type: "object"
    properties:
      login:
        type: "string"
