/**
 * BringAlong Server REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface BringDemandEto { 
    id?: number;
    modificationCounter?: number;
    item: string;
    dropHint?: string;
    deadline?: Date;
    estimatedAmount?: number;
    currency: string;
    acceptedByUser?: number;
    userId: number;
}
