/**
 * BringAlong Server REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Pageable } from './pageable';
import { StringSearchConfigTo } from './stringSearchConfigTo';


export interface BringDemandSearchCriteriaTo { 
    pageable?: Pageable;
    item?: string;
    dropHint?: string;
    deadline?: Date;
    estimatedAmount?: number;
    currency?: string;
    lon?: number;
    lat?: number;
    range?: number;
    acceptedByUser?: number;
    userId?: number;
    itemOption?: StringSearchConfigTo;
    dropHintOption?: StringSearchConfigTo;
    currencyOption?: StringSearchConfigTo;
}
