/**
 * bringalong
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: todo@test.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface StoreOrder { 
    id?: number;
    /**
     * Only filled when order is marked for pickup.
     */
    name?: string;
    /**
     * Shortend address. Complete address when order is marked for pickup.
     */
    address?: string;
    /**
     * Code needed to pick of the order. Only filled when order is marked for pickup.
     */
    pickupcode?: string;
}
