/**
 * BringAlong Server REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface StringSearchConfigTo { 
    ignoreCase?: boolean;
    matchSubstring?: boolean;
    likeSyntax?: StringSearchConfigTo.LikeSyntaxEnum;
    operator?: StringSearchConfigTo.OperatorEnum;
}
export namespace StringSearchConfigTo {
    export type LikeSyntaxEnum = 'GLOB' | 'SQL';
    export const LikeSyntaxEnum = {
        GLOB: 'GLOB' as LikeSyntaxEnum,
        SQL: 'SQL' as LikeSyntaxEnum
    };
    export type OperatorEnum = 'EQ' | 'NE' | 'LT' | 'LE' | 'GT' | 'GE' | 'LIKE' | 'NOT_LIKE';
    export const OperatorEnum = {
        EQ: 'EQ' as OperatorEnum,
        NE: 'NE' as OperatorEnum,
        LT: 'LT' as OperatorEnum,
        LE: 'LE' as OperatorEnum,
        GT: 'GT' as OperatorEnum,
        GE: 'GE' as OperatorEnum,
        LIKE: 'LIKE' as OperatorEnum,
        NOTLIKE: 'NOT_LIKE' as OperatorEnum
    };
}
