/**
 * BringAlong Server REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Address } from './address';


export interface UserEto { 
    id?: number;
    modificationCounter?: number;
    login?: string;
    surname?: string;
    possiblePaymentOptions?: Array<UserEto.PossiblePaymentOptionsEnum>;
    forename?: string;
    address?: Address;
}
export namespace UserEto {
    export type PossiblePaymentOptionsEnum = 'PAYPAL' | 'SEPA' | 'PAYPALME';
    export const PossiblePaymentOptionsEnum = {
        PAYPAL: 'PAYPAL' as PossiblePaymentOptionsEnum,
        SEPA: 'SEPA' as PossiblePaymentOptionsEnum,
        PAYPALME: 'PAYPALME' as PossiblePaymentOptionsEnum
    };
}
