/**
 * BringAlong Server REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AddressEto } from './addressEto';
import { PaymentOptionEto } from './paymentOptionEto';
import { UserEto } from './userEto';


export interface UserCto { 
    user?: UserEto;
    address?: AddressEto;
    acceptedPaymentOptions?: Array<PaymentOptionEto>;
}
