language: java
jdk:
  - openjdk11
cache:
  directories:
    - "$HOME/.m2/repository"
    - npm
services:
  - xvfb
stages:
  - name: CI & CD
jobs:
  include:
    - stage: CI & CD
      script: mvn clean install -Pweb-client
      deploy:
        provider: heroku
        api_key:
          secure: bLT9bhFEVw290dIq9DfetpAz6O4diYfe8R33vZs0D+ly0fYDzExVsJv28XPyTLltkpcnyJZN37c8KXOHu4MKh/Un4JS/HIb2WRyC1qzis0UZuICuNGshN1Zjn0VMeUXyvwZjQ/vcodXsH0xe0XpWQfuz5JRKiQ2UbKFhZoXgyfPKNhx+DpVK/ms7JDHBSOHqYMq3Y+60TVo8CZVjlgZAm8oaL+HyPzL+iN3p3icX0zgMXut3bwSlqichvrqXE0pBFKhjzrO8+NKkMDfA2IgVPQYV0sVTljQs+rrEM8OmQnj0t07k99YR7Do1BpTkARMFb5zLkLdXM+WQrL4uTNa0zHAzL6iGpia5HnnobIEY1QDhN/M+uE93QaN9LuDmQ7VNivLLRSuTSp0sgfmC4dN9GXn9UdU9lgzXZN1JBCfAjPwIxr875viIIVE+vt4Ul6ZMDvKen/G3aiEQdjp2XDCbIXACdkU9+gnih61foocxYuxZv2Lg77roWjfzaeWCrspGL1A8Uye8lyqWr0chEa29rY/TCcfeeD+x4OE45O1lqKQr6NiFbgynWBlUoS+WiSI6f5VQ6AWlFCwm6fMsfjD92GpDsWQPlLLl6SA72m6N+Nu3BC5I0fXBKP8iSjR53U+8Yovhek4P85hfAGsVMwTOBjz3cOKS7JEdRSds55RW7WQ=
        app: bringalongorg
        run:
          - java -Dserver.port=$PORT $JAVA_OPTS -jar server/target/bringalong-server-bootified.war
