swagger: "2.0"
info:
  description: ""
  version: "1.0.0"
  title: "bringalong"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "todo@test.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "test.host.com"
basePath: "/"
schemes:
- "https"
- "http"
paths:
  /stores/{plz}:
    get:
      summary: ""
      description: ""
      operationId: "searchStores"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "plz"
        description: ""
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/SearchStoresResult"
  /orders/{storeId}:
    get:
      summary: ""
      description: ""
      operationId: "loadOrders"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "storeId"
        description: ""
        required: true
        type: "integer"
        format: "int32"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/LoadStoreOrdersResult"
  /products/{storeId}:
    get:
      summary: ""
      description: ""
      operationId: "loadProductsForStore"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "storeId"
        description: ""
        required: true
        type: "integer"
        format: "int32"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/LoadProductsForStoreResult"
definitions:
  SearchStoresResult:
    type: "object"
    properties:
      stores:
        type: "array"
        items: 
          $ref: "#/definitions/Store"
  Store:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
      name:
        type: "string"
      address:
        type: "string"
  LoadStoreOrdersResult:
    type: "object"
    properties:
      orders:
        type: "array"
        items: 
          $ref: "#/definitions/StoreOrder"
  StoreOrder:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
      address:
        type: "string"
      pickupcode:
        type: "string"
        description: "Code needed to pick of the order. Only filled when order is marked for pickup."
  LoadProductsForStoreResult:
    type: "object"
    properties:
      products:
        type: "array"
        items: 
          $ref: "#/definitions/Product"
  Product:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
      name:
        type: "string"
      price:
        type: "number"