swagger: "2.0"
info:
  description: ""
  version: "1.0.0"
  title: "bringalong"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "todo@test.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "test.host.com"
basePath: "/"
schemes:
- "https"
- "http"
paths:
  /stores/{plz}:
    get:
      summary: ""
      description: ""
      operationId: "searchStores"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "plz"
        description: ""
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/SearchStoresResult"
  /orders/{storeId}:
    get:
      summary: ""
      description: ""
      operationId: "getStoreOrders"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "storeId"
        description: ""
        required: true
        type: "integer"
        format: "int32"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/GetStoreOrdersResult"
    post:
      summary: ""
      description: ""
      operationId: "createOrder"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "storeId"
        description: ""
        required: true
        type: "integer"
        format: "int32"
      - in: "body"
        name: "body"
        schema:
          $ref: "#/definitions/CreateOrderRequest"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/CreateOrderResult"
  /orders:
    get:
      summary: ""
      description: ""
      operationId: "getOwnOrders"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/GetOwnOrdersResult"
  /order/{orderId}:
    post:
      summary: ""
      description: ""
      operationId: "bringOrder"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "orderId"
        description: ""
        required: true
        type: "integer"
        format: "int32"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/BringOrderResult"
  /products/{storeId}:
    get:
      summary: ""
      description: ""
      operationId: "getProductsForStore"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "storeId"
        description: ""
        required: true
        type: "integer"
        format: "int32"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/GetProductsForStoreResult"
definitions:
  SearchStoresResult:
    type: "object"
    properties:
      stores:
        type: "array"
        items: 
          $ref: "#/definitions/Store"
  Store:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
      name:
        type: "string"
      address:
        type: "string"
  GetStoreOrdersResult:
    type: "object"
    properties:
      orders:
        type: "array"
        items: 
          $ref: "#/definitions/StoreOrder"
  StoreOrder:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
      address:
        type: "string"
        description: "Shortend address"
      pickupcode:
        type: "string"
        description: "Code needed to pick of the order. Only filled when order is marked for pickup."
  GetOwnOrdersResult:
    type: "object"
    properties:
      orders:
        type: "array"
        items: 
          $ref: "#/definitions/OwnOrder"
  OwnOrder:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
      storeId:
        type: "integer"
        format: "int32"
      startDate:
        type: "string"
      startTime:
        type: "string"
      endDate:
        type: "string"
      endTime:
        type: "string"
      orderItems:
        type: "array"
        items: 
          $ref: "#/definitions/OrderItem"
  GetProductsForStoreResult:
    type: "object"
    properties:
      products:
        type: "array"
        items: 
          $ref: "#/definitions/Product"
  Product:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
      name:
        type: "string"
      price:
        type: "number"
  CreateOrderRequest:
    type: "object"
    properties:
      startDate:
        type: "string"
      startTime:
        type: "string"
      endDate:
        type: "string"
      endTime:
        type: "string"
      orderItems:
        type: "array"
        items: 
          $ref: "#/definitions/OrderItem"
  OrderItem:
    type: "object"
    properties:
      productId:
        type: "integer"
        format: "int32"
      amount:
        type: "integer"
        format: "int32"
  CreateOrderResult:
    type: "object"
    properties:
      orderId:
        type: "integer"
        format: "int32"
  BringOrderResult:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
      address:
        type: "string"
        description: "Complete address"
      pickupcode:
        type: "string"
        description: "Code needed to pick of the order. Only filled when order is marked for pickup."